name: td3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cffi==1.15.0
    - charset-normalizer==2.0.10
    - click==8.0.3
    - cloudpickle==2.0.0
    - configparser==5.2.0
    - cython==0.29.24
    - docker-pycreds==0.4.0
    - fasteners==0.16.3
    - gitdb==4.0.9
    - gitpython==3.1.26
    - glfw==2.4.0
    - gym==0.21.0
    - gym-notices==0.0.6
    - idna==3.3
    - imageio==2.13.0
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.11.3
    - mouseinfo==0.1.3
    - mujoco-py==2.0.2.13
    - numpy==1.21.4
    - pathtools==0.1.2
    - pillow==8.4.0
    - progress==1.6
    - promise==2.3
    - protobuf==3.19.3
    - psutil==5.9.0
    - pyautogui==0.9.53
    - pycparser==2.21
    - pygetwindow==0.0.9
    - pymsgbox==1.0.9
    - pyperclip==1.8.2
    - pyrect==0.1.4
    - pyscreeze==0.1.28
    - python-dateutil==2.8.2
    - python3-xlib==0.15
    - pytweening==1.0.4
    - pyyaml==6.0
    - requests==2.27.1
    - sentry-sdk==1.5.2
    - setproctitle==1.2.3
    - shortuuid==1.0.8
    - six==1.16.0
    - smmap==5.0.0
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - torch==1.10.2
    - typing-extensions==4.0.0
    - urllib3==1.26.8
    - wandb==0.12.16
    - yaspin==2.1.0
    - zipp==3.6.0
prefix: /home/noah/anaconda3/envs/td3
