name: pytorch_sac
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.13.0=py36h06a4308_0
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.5.30=py36h06a4308_0
  - cffi=1.14.6=py36h400218f_0
  - cudatoolkit=9.2=0
  - cudnn=7.6.5=cuda9.2_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=h5e70eb0_2
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - python=3.6.13=h12debd9_1
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.8
    - click==8.0.4
    - cloudpickle==2.0.0
    - cython==0.29.24
    - dataclasses==0.8
    - dm-control==0.0.364896371
    - dm-env==1.5
    - dm-tree==0.1.6
    - dmc2gym==1.0.0
    - docker-pycreds==0.4.0
    - fasteners==0.16.3
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.18
    - glfw==2.4.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - gym==0.21.0
    - h5py==3.1.0
    - hydra-core==0.11.3
    - idna==3.3
    - imageio==2.13.1
    - importlib-metadata==4.8.2
    - labmaze==1.0.5
    - lxml==4.6.4
    - markdown==3.3.6
    - mujoco-py==2.1.2.14
    - oauthlib==3.1.1
    - omegaconf==1.4.1
    - pathtools==0.1.2
    - pillow==8.4.0
    - progress==1.6
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyopengl==3.1.5
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scipy==1.5.4
    - sentry-sdk==1.5.8
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - smmap==5.0.0
    - tb-nightly==2.8.0a20211202
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - torch==1.10.0
    - tqdm==4.62.3
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - wandb==0.12.11
    - werkzeug==2.0.2
    - yaspin==2.1.0
    - zipp==3.6.0
prefix: /home/noah/anaconda3/envs/pytorch_sac
